name: Build macOS Executable

on:
  push:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.6'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app
          pip install -r requirements.txt  # Include your dependencies

      - name: Compile with PyInstaller
        run: |
          py2applet --make-setup main.py
          rm -rf build dist
          python setup.py py2app -A
      - name: available files
        run: |
          ls dist

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: macOS-executable
          path: build
