name: Build Executable

on:
  push:
    branches:
      - main  # or your target branch

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Executable
      run: |
        pyinstaller --onefile main.py  # specify your script

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: main
        path: /Users/runner/work/CareViewScrapper/CareViewScrapper/dist/main  # path to your executable
